projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        documents: /**/*.graphql
        codeGenTarget: typescript
        generatedFileName: /grapgql/API.ts
        docsFilePath: .
        region: us-east-1
        apiId: tyeiexbig5doxchzbvdjz2rqam
        frontend: javascript
        framework: react
        maxDepth: 4
extensions:
  amplify:
    version: 3
